/**
 * @tracearr/shared - Shared types, schemas, and constants
 */

// Type exports
export type {
  // Server
  ServerType,
  Server,
  // User
  User,
  ServerUser,
  ServerUserWithIdentity,
  ServerUserDetail,
  ServerUserFullDetail,
  ViolationSummary,
  UserRole,
  AuthUser,
  SetupStatus,
  UserLocation,
  UserDevice,
  UserMergeResult,
  ServerUserSplitResult,
  MergeSuggestionIdentity,
  MergeSuggestion,
  // Session
  SessionState,
  MediaType,
  Session,
  SessionSegment,
  SessionWithDetails,
  ActiveSession,
  SourceVideoDetails,
  SourceAudioDetails,
  StreamVideoDetails,
  StreamAudioDetails,
  TranscodeInfo,
  SubtitleInfo,
  StreamDetailFields,
  // V1 rule params, still read by the automation migration
  ImpossibleTravelParams,
  SimultaneousLocationsParams,
  DeviceVelocityParams,
  ConcurrentStreamsParams,
  GeoRestrictionMode,
  GeoRestrictionParams,
  AccountInactivityUnit,
  AccountInactivityParams,
  EngineAutomation,
  // Violation
  ViolationSeverity,
  Violation,
  ViolationWithDetails,
  ViolationSessionInfo,
  // Stats
  DashboardStats,
  PlayStats,
  UserStats,
  LocationStats,
  LocationStatsSummary,
  LocationStatsResponse,
  LibraryStats,
  DayOfWeekStats,
  HourOfDayStats,
  QualityStats,
  TopUserStats,
  TopContentStats,
  PlatformStats,
  // Server resource stats
  ServerResourceDataPoint,
  ServerResourceStats,
  // Server bandwidth stats
  ServerBandwidthDataPoint,
  ServerBandwidthStats,
  BandwidthAccount,
  BandwidthDevice,
  BandwidthSample,
  ServerLiveStats,
  // Settings
  Settings,
  UnitSystem,
  ImageCacheStatus,
  // Tailscale
  TailscaleStatus,
  TailscaleExitNode,
  TailscaleInfo,
  // Tautulli import
  TautulliImportProgress,
  TautulliImportResult,
  // Jellystat import
  JellystatImportProgress,
  JellystatImportResult,
  // Playback Reporting import
  PlaybackReportingImportProgress,
  PlaybackReportingImportResult,
  // Library sync
  LibrarySyncProgress,
  // Heavy ops coordination
  HeavyOpsWaitingFor,
  // Maintenance jobs
  MaintenanceJobType,
  MaintenanceJobStatus,
  MaintenanceJobProgress,
  MaintenanceJobResult,
  // Running tasks
  RunningTaskType,
  RunningTask,
  RunningTasksResponse,
  // WebSocket
  ServerToClientEvents,
  ClientToServerEvents,
  // API
  PaginatedResponse,
  ApiError,
  // History page types
  HistoryAggregates,
  HistorySessionResponse,
  FilterOptionItem,
  UserFilterOption,
  ServerFilterOption,
  CountryOption,
  HistoryFilterOptions,
  AutomationFilterOptions,
  // Mobile
  MobileToken,
  MobileSession,
  MobileConfig,
  MobilePairRequest,
  MobilePairResponse,
  MobilePairTokenResponse,
  MobileQRPayload,
  NotificationEventType,
  NotificationPreferences,
  RateLimitStatus,
  NotificationPreferencesWithStatus,
  EncryptedPushPayload,
  PushNotificationPayload,
  // SSE (Server-Sent Events)
  SSEConnectionState,
  PlexSSENotification,
  PlexPlaySessionNotification,
  PlexActivityNotification,
  PlexStatusNotification,
  PlexTranscodeNotification,
  PlexTimelineEntry,
  SSEConnectionStatus,
  ServerConnectionStatus,
  PluginIssue,
  // Termination logs
  TerminationTrigger,
  TerminationLogWithDetails,
  // Plex server discovery
  PlexDiscoveredConnection,
  PlexDiscoveredServer,
  PlexAvailableServersResponse,
  PlexConnectionError,
  PlexConnectionErrorCode,
  // Plex account management
  PlexAccount,
  PlexAccountsResponse,
  LinkPlexAccountRequest,
  LinkPlexAccountResponse,
  UnlinkPlexAccountResponse,
  ReauthorizePlexAccountResponse,
  ReauthorizedServer,
  ReauthorizedServerStatus,
  // Version
  VersionInfo,
  // Backup & Restore
  BackupMetadata,
  RestorePhase,
  RestoreProgress,
  BackupType,
  BackupListItem,
  BackupScheduleType,
  // Engagement tracking
  EngagementTier,
  UserBehaviorType,
  ContentEngagement,
  TopContentEngagement,
  ShowEngagement,
  UserEngagementProfile,
  EngagementTierBreakdown,
  EngagementStats,
  ShowStatsResponse,
  // Device compatibility
  DeviceCompatibilityRow,
  DeviceCompatibilityResponse,
  DeviceCompatibilityMatrix,
  DeviceHealthRow,
  DeviceHealthResponse,
  TranscodeHotspotRow,
  TranscodeHotspotsResponse,
  // Top transcoding users
  TopTranscodingUserRow,
  TopTranscodingUsersResponse,
  // Bandwidth stats
  DailyBandwidthRow,
  DailyBandwidthResponse,
  BandwidthTopUser,
  BandwidthTopUsersResponse,
  BandwidthSummaryServerKpis,
  BandwidthSummary,
  // Library statistics
  LibraryStatsResponse,
  GrowthDataPoint,
  LibraryGrowthResponse,
  QualityDataPoint,
  LibraryQualityResponse,
  StorageHistoryPoint,
  StoragePrediction,
  LibraryStorageResponse,
  MatchType,
  DuplicateItem,
  DuplicateItemVersion,
  DuplicateGroup,
  DuplicatesSummary,
  DuplicatesResponse,
  StaleCategory,
  StaleItem,
  StaleSummary,
  StaleResponse,
  WatchItem,
  WatchSummary,
  WatchResponse,
  CompletionStatus,
  CompletionItem,
  SeasonCompletion,
  SeriesCompletion,
  CompletionSummary,
  CompletionPaginationInfo,
  CompletionResponse,
  WatchedState,
  CatalogRowServerEntry,
  CatalogRow,
  CatalogResponseMeta,
  CatalogResponse,
  CatalogLetterBucket,
  CatalogLettersResponse,
  ShelfRow,
  RecentlyAddedShelfRow,
  MostPopularShelfRow,
  DeadWeightRow,
  ShelvesKpiWatchedInPeriod,
  ShelvesKpiNewlyAdded,
  ShelvesKpiDeadWeight,
  ShelvesKpis,
  ShelvesResponseMeta,
  ShelvesResponse,
  ShelvesPeriod,
  GenreRow,
  GenresResponse,
  MediaVersionEntry,
  MediaAvailabilityEntry,
  MediaReplacedCopy,
  MediaDetailResponse,
  MediaChildEntry,
  MediaChildrenResponse,
  MediaStatsMeasures,
  MediaStatsWindow,
  MediaStatsResponse,
  MediaWatcherEntry,
  MediaWatchersResponse,
  MediaPlatformBreakdownEntry,
  MediaPlatformBreakdownResponse,
  SeasonHeatEpisode,
  SeasonHeatSeason,
  MediaSeasonHeatResponse,
  BingeShow,
  HourlyDistribution,
  MonthlyTrend,
  PatternsResponse,
  ValueCategory,
  RoiItem,
  RoiSummary,
  ValueThresholds,
  RoiResponse,
  TopMovie,
  TopMoviesSummary,
  TopMoviesResponse,
  TopShow,
  TopShowsSummary,
  TopShowsResponse,
  CodecEntry,
  CodecBreakdown,
  LibraryCodecsResponse,
  ResolutionEntry,
  ResolutionBreakdown,
  LibraryResolutionResponse,
  LibraryOption,
  LibrariesResponse,
} from './types.js';

// Destination type exports
export type {
  DestinationKind,
  DestinationFieldDescriptor,
  DestinationFieldOption,
  DestinationDescriptor,
  Destination,
  DestinationTestResult,
  CreateDestinationInput,
  UpdateDestinationInput,
  NotificationToast,
  EmailSecurity,
} from './destinations.js';

// Automation type exports
export type {
  AutomationKind,
  TriggerContext,
  TriggerGroup,
  TriggerType,
  TriggerNode,
  RunOutcome,
  Automation,
  AutomationScopeRef,
  AutomationTemplateRef,
  AutomationOrigin,
  AutomationRunSummary,
  AutomationRun,
  RunSubject,
  RunSubjectKind,
  RunSessionContext,
  RunFinishedEvent,
  CreateAutomationInput,
  UpdateAutomationInput,
  AutomationSortField,
  AutomationSource,
  AutomationListQuery,
  RunSortField,
  RunListQuery,
  RunCounts,
  NearMissReason,
  NearMissEntry,
  ConditionFieldDescriptor,
  // Condition family
  Operator,
  ScopeField,
  LibraryItemType,
  ConditionField,
  ConditionValue,
  TranscodingConditionValue,
  VideoResolution,
  DeviceType,
  Platform,
  MediaTypeEnum,
  NodeFields,
  Condition,
  ConditionGroup,
  ConditionMatch,
  AutomationConditions,
  ConditionEvidence,
  GroupEvidence,
  ActionResult,
  LeafActionType,
  LeafAction,
  IfAction,
  TemplateInput,
  TemplateDefinition,
  TemplateEnvelope,
  ShareCodeReason,
  DryRunRequest,
  DryRunSubject,
  DryRunCondition,
  DryRunAction,
  DryRunSample,
  DryRunResponse,
} from './automations/index.js';

// Automation constants and schemas
export {
  AUTOMATION_KINDS,
  TRIGGERS,
  TRIGGER_GROUPS,
  TRIGGER_TYPES,
  CONDITION_FIELDS,
  operatorSchema,
  conditionValueSchema,
  conditionSchema,
  ACTIONS,
  ACTION_TYPES,
  LEAF_ACTION_TYPES,
  RUN_OUTCOMES,
  RETENTION_DEFAULTS,
  AUTOMATION_NAME_MAX,
  AUTOMATION_DESCRIPTION_MAX,
  AUTOMATION_SORT_FIELDS,
  AUTOMATION_SOURCES,
  RUN_SORT_FIELDS,
  triggerNodeSchema,
  heldForParamsSchema,
  inactiveForParamsSchema,
  conditionGroupSchema,
  automationDefinitionSchema,
  createAutomationSchema,
  updateAutomationSchema,
  automationListQuerySchema,
  dryRunRequestSchema,
  runListQuerySchema,
  runCountsQuerySchema,
  NEAR_MISS_REASONS,
  nearMissEntrySchema,
  contextOf,
  contextSupplies,
  fieldsAvailableFor,
  TEMPLATE_GROUPS,
  TEMPLATE_SCHEMA_VERSION,
  TEMPLATE_MIN_SERVER_VERSION,
  templateEnvelopeSchema,
  materializeTemplate,
  slotValueFor,
  liftAutomation,
  TemplateBindingError,
  ShareCodeError,
  assertShareDepth,
  canonicalJson,
  fingerprintOf,
  encodeShareCode,
  decodeShareCode,
} from './automations/index.js';

// Schema exports
export {
  // Common
  uuidSchema,
  serverIdsQuerySchema,
  libraryKeySchema,
  paginationSchema,
  booleanStringSchema,
  // Auth
  loginSchema,
  callbackSchema,
  // Server
  createServerSchema,
  PUBLIC_URL_PLEX_MESSAGE,
  apiKeyConnectSchema,
  publicUrlSchema,
  serverIdParamSchema,
  reorderServersSchema,
  updateServerSchema,
  // User
  updateUserSchema,
  updateUserIdentitySchema,
  userIdParamSchema,
  identityScopeQuerySchema,
  identityScopedPaginationSchema,
  mergeUsersBodySchema,
  mergeUserParamSchema,
  splitServerUserParamSchema,
  USER_SORT_FIELDS,
  userRosterFilterSchema,
  userListQuerySchema,
  bulkResetTrustBodySchema,
  // Session
  sessionQuerySchema,
  historyQuerySchema,
  historyAggregatesQuerySchema,
  filterOptionsQuerySchema,
  sessionIdParamSchema,
  terminateSessionBodySchema,
  // Rule
  impossibleTravelParamsSchema,
  simultaneousLocationsParamsSchema,
  deviceVelocityParamsSchema,
  concurrentStreamsParamsSchema,
  geoRestrictionParamsSchema,
  accountInactivityParamsSchema,
  // Rule V2
  automationConditionsSchema,
  actionTypeSchema,
  actionSchema,
  sendActionSchema,
  trustActionSchema,
  hasAtMostOneScope,
  AUTOMATION_SCOPE_ERROR_MESSAGE,
  scopeAllowsCrossServerEnforcement,
  AUTOMATION_CROSS_SERVER_ENFORCEMENT_ERROR_MESSAGE,
  // Bulk operations
  bulkUpdateAutomationsSchema,
  bulkDeleteAutomationsSchema,
  // Violation
  VIOLATION_SORT_FIELDS,
  violationRosterFilterSchema,
  violationQuerySchema,
  violationBulkBodySchema,
  violationIdParamSchema,
  // Stats
  serverIdFilterSchema,
  dashboardQuerySchema,
  timezoneSchema,
  statPeriodSchema,
  dateValidationRefinements,
  statsQuerySchema,
  locationStatsQuerySchema,
  // Settings
  updateSettingsSchema,
  // Tailscale
  tailscaleEnableSchema,
  tailscaleExitNodeSchema,
  // Tautulli import
  tautulliImportSchema,
  // Jellystat import
  jellystatPlayStateSchema,
  jellystatTranscodingInfoSchema,
  jellystatPlaybackActivitySchema,
  jellystatBackupSchema,
  jellystatImportBodySchema,
  importJobStatusSchema,
  // Playback Reporting import
  playbackReportingImportSchema,
  playbackReportingTestSchema,
  // Engagement tracking
  engagementTierSchema,
  userBehaviorTypeSchema,
  engagementQuerySchema,
  showsQuerySchema,
  // Library stats
  libraryStatsQuerySchema,
  libraryStatusQuerySchema,
  libraryGrowthQuerySchema,
  libraryQualityQuerySchema,
  libraryStorageQuerySchema,
  libraryDuplicatesQuerySchema,
  libraryStaleQuerySchema,
  libraryWatchQuerySchema,
  libraryRoiQuerySchema,
  libraryPatternsQuerySchema,
  libraryCompletionQuerySchema,
  topContentQuerySchema,
  shelvesQuerySchema,
} from './schemas.js';

// Destination descriptors and schemas
export {
  DESTINATION_KINDS,
  DESTINATION_TYPES,
  NOTIFICATION_EVENT_TYPES,
  SUBSCRIBABLE_EVENTS,
  destinationConfigSchema,
  configSchemaForFields,
  notificationEventTypeSchema,
  createDestinationSchema,
  updateDestinationSchema,
  EMAIL_SECURITY,
  EMAIL_SMTP_PRESETS,
  addressList,
} from './destinations.js';

// Schema input type exports
export type { SubscribableEvent } from './destinations.js';

// Newsletter constants, schemas and API shapes
export {
  NEWSLETTER_SECTION_MAX,
  NEWSLETTER_MOST_WATCHED_MAX,
  NEWSLETTER_SEASONS_PER_SHOW_MAX,
  NEWSLETTER_WINDOW_MAX_DAYS,
  NEWSLETTER_EXTRA_ADDRESSES_MAX,
  NEWSLETTER_EXCLUDED_USERS_MAX,
  NEWSLETTER_SENDER_NAME_MAX,
  NEWSLETTER_SEND_TRIGGERS,
  NEWSLETTER_SEND_OUTCOMES,
  NEWSLETTER_RECIPIENT_STATUSES,
  NEWSLETTER_IMAGE_MODES,
  EMAIL_SUPPRESSION_REASONS,
  DEFAULT_NEWSLETTER_SUBJECT,
  DEFAULT_NEWSLETTER_SECTIONS,
  cronExpressionSchema,
  newsletterScheduleSchema,
  newsletterWindowSchema,
  newsletterSectionsSchema,
  newsletterScopeSchema,
  NEWSLETTER_SCOPE_LIBRARIES_MAX,
  newsletterScopeLibrarySchema,
  newsletterRecipientsSchema,
  newsletterLinksSchema,
  DEFAULT_NEWSLETTER_LINKS,
  createNewsletterSchema,
  updateNewsletterSchema,
  newsletterTestSendSchema,
  newsletterPreviewDraftSchema,
  emailSuppressionCreateSchema,
  newsletterSendsQuerySchema,
  newsletterCron,
  resolveSenderName,
  variantKey,
  variantServerIds,
  needsSenderName,
  variantKeySchema,
  EMAIL_LOGO_MODES,
  emailBrandingSchema,
  emailBrandingReadSchema,
  DEFAULT_EMAIL_BRANDING,
  NEWSLETTER_VIEW_TOKEN_LENGTH,
  NEWSLETTER_SNAPSHOT_RETENTION_DAYS,
  NEWSLETTER_SEND_RETENTION_DAYS,
  NEWSLETTER_EXCLUDED_REASONS,
} from './newsletters.js';
export type {
  NewsletterSendTrigger,
  NewsletterSendOutcome,
  NewsletterRecipientStatus,
  NewsletterImageMode,
  EmailSuppressionReason,
  NewsletterSchedule,
  NewsletterWindow,
  NewsletterSections,
  NewsletterScope,
  NewsletterScopeLibrary,
  NewsletterRecipients,
  NewsletterLinks,
  CreateNewsletterInput,
  UpdateNewsletterInput,
  Newsletter,
  NewsletterSendSummary,
  NewsletterSendVariant,
  NewsletterSendRecipient,
  NewsletterSendDetail,
  NewsletterSendsPage,
  NewsletterRecipientPerson,
  NewsletterExcludedReason,
  NewsletterExcludedPerson,
  NewsletterResolvedRecipient,
  NewsletterRecipientsView,
  EmailSuppression,
  NewsletterPreview,
  NewsletterPreviewDraftInput,
  NewsletterPreviewVariant,
  NewsletterVariantsView,
  NewsletterSectionCounts,
  EmailLogoMode,
  EmailBrandingSettings,
  NewsletterSendHtml,
} from './newsletters.js';

// Rich text for newsletter intro and outro
export {
  EMAIL_RICH_TEXT_MAX_CHARS,
  EMAIL_RICH_TEXT_MAX_BLOCKS,
  EMAIL_RICH_TEXT_MAX_LIST_ITEMS,
  EMAIL_RICH_TEXT_MAX_MARKS,
  EMAIL_RICH_TEXT_MAX_WEIGHT,
  emailRichTextHrefSchema,
  emailRichTextDocSchema,
  emailRichTextLength,
  emailRichTextWeight,
  normalizeEmailRichText,
} from './emailRichText.js';
export type {
  EmailRichTextDoc,
  EmailRichTextBlock,
  EmailRichTextParagraph,
  EmailRichTextInline,
  EmailRichTextMark,
} from './emailRichText.js';

export type {
  LoginInput,
  CallbackInput,
  CreateServerInput,
  ReorderServersInput,
  UpdateServerInput,
  UpdateUserInput,
  UpdateUserIdentityInput,
  IdentityScopeQuery,
  MergeUsersBody,
  SessionQueryInput,
  HistoryQueryInput,
  HistoryAggregatesQueryInput,
  FilterOptionsQueryInput,
  // Bulk operations types
  BulkUpdateAutomationsInput,
  BulkDeleteAutomationsInput,
  ViolationRosterFilters,
  ViolationBulkBody,
  ViolationSortField,
  UserSortField,
  UserRosterFilters,
  ServerIdFilterInput,
  DashboardQueryInput,
  StatPeriod,
  StatsQueryInput,
  LocationStatsQueryInput,
  UpdateSettingsInput,
  TautulliImportInput,
  // Jellystat types
  JellystatPlayState,
  JellystatTranscodingInfo,
  JellystatPlaybackActivity,
  JellystatBackup,
  JellystatImportBody,
  ImportJobStatus,
  // Engagement tracking
  EngagementQueryInput,
  ShowsQueryInput,
  // Library stats
  LibraryStatsQueryInput,
  LibraryStatusQueryInput,
  LibraryGrowthQueryInput,
  LibraryQualityQueryInput,
  LibraryStorageQueryInput,
  LibraryDuplicatesQueryInput,
  LibraryStaleQueryInput,
  LibraryWatchQueryInput,
  LibraryRoiQueryInput,
  LibraryPatternsQueryInput,
  LibraryCompletionQueryInput,
  TopContentQueryInput,
  ShelvesQueryInput,
  // Session target type
  SessionTarget,
  // Rule V2 action family
  ActionType,
  Action,
  SendAction,
  TrustAction,
  KillStreamAction,
  MessageClientAction,
  AutomationActions,
} from './schemas.js';

// Constant exports
export {
  IDENTITY_AWARE_CONDITION_FIELDS,
  SEVERITY_LEVELS,
  getSeverityPriority,
  type SeverityPriority,
  WS_EVENTS,
  REDIS_KEYS,
  setRedisPrefix,
  getRedisPrefix,
  CACHE_TTL,
  NOTIFICATION_EVENTS,
  API_VERSION,
  API_BASE_PATH,
  API_VERSION_V2,
  API_V2_BASE_PATH,
  JWT_CONFIG,
  POLLING_INTERVALS,
  POLLER_CONFIG,
  PAGINATION,
  GEOIP_CONFIG,
  TIME_MS,
  MERGE_SAME_SERVER_CONFIRMATION_REQUIRED,
  SESSION_LIMITS,
  SESSION_WRITE_RETRY,
  SERVER_STATS_CONFIG,
  liveStatsRetentionSeconds,
  BANDWIDTH_STATS_CONFIG,
  // SSE
  SSE_CONFIG,
  PLEX_SSE_EVENTS,
  SSE_STATE,
  // Unit conversion
  UNIT_CONVERSION,
  BYTES_PER_GB,
  kmToMiles,
  milesToKm,
  formatDistance,
  formatSpeed,
  formatBitrate,
  formatMediaTech,
  getResolutionLabel,
  formatResolutionDisplay,
  type ResolutionLabel,
  formatAudioChannels,
  getDistanceUnit,
  getSpeedUnit,
  toMetricDistance,
  fromMetricDistance,
  formatConditionFieldValue,
  // Server colors
  SERVER_COLOR_PALETTE,
  SERVER_TYPE_BRAND_COLORS,
  pickServerColor,
  // Timezone utilities
  getClientTimezone,
  isValidTimezone,
  // Multi-version media
  LEGACY_VERSION_SENTINEL,
  // Poster cache
  POSTER_IMAGE_SIZE,
} from './constants.js';

// Role helper exports
export { ROLE_PERMISSIONS, LOGIN_ROLES, canLogin, hasMinRole, isOwner, isActive } from './types.js';

// Session constants
export { MEDIA_TYPES, DEFAULT_STREAM_DETAILS } from './types.js';

// Backup constants
export { RESTORE_PHASES } from './types.js';

// Violation utilities
export {
  collectViolationSessions,
  getViolationDescription,
  getViolationDetails,
  formatEvidenceDescription,
  formatEvidenceDetails,
  formatUserList,
  CONDITION_FIELD_LABELS,
  OPERATOR_LABELS,
} from './violations.js';

// Media display utilities
export { formatEpisodeLabel, type FormatEpisodeLabelOptions } from './media.js';

// Alphabet rail letters
export { LETTER_RAIL_ALPHABET } from './catalogLetters.js';

// List-query contract
export { listSortSchema, listDateBoundSchema, listPageCount } from './listQuery.js';
export type { ListMeta, ListResponse } from './listQuery.js';

// Resolution classification
export {
  RESOLUTION_TIERS,
  classifyByDimensions,
  normalizeResolutionLabel,
  resolutionTierRank,
  resolutionBucket,
  resolutionBucketSpellings,
  resolutionAboveSdSpellings,
  resolutionSpellingRanks,
  normalizeResolution,
  type ResolutionInput,
  type ResolutionBucket,
} from './resolution.js';

// Dynamic range (HDR/SDR) classification
export {
  DYNAMIC_RANGE_SDR_TOKEN,
  DYNAMIC_RANGE_TOKENS,
  normalizeDynamicRange,
  type DynamicRangeToken,
} from './dynamicRange.js';

// Server-scope selection (cache-key and query-param builders)
export {
  ALL_SERVERS,
  serverScopeFromIds,
  serverScopeKey,
  serverScopeParamEntries,
  type ServerScope,
} from './serverScope.js';

export {
  buildMediaServerItemUrl,
  isPubliclyRoutableUrl,
  memberFacingUrl,
  type MediaServerItemLinkInput,
} from './mediaServerLinks.js';
